# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTickSummary',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(default='stocks', max_length=12)),
                ('sym', models.CharField(max_length=12)),
                ('dt', models.DateTimeField()),
                ('o', models.BigIntegerField()),
                ('h', models.BigIntegerField()),
                ('l', models.BigIntegerField()),
                ('c', models.BigIntegerField()),
                ('vol', models.BigIntegerField()),
            ],
        ),
        migrations.AddIndex(
            model_name='assetticksummary',
            index=models.Index(fields=['type', 'sym', 'dt'], name='asset_tick_summary_comp_idx'),
        ),
        migrations.AddIndex(
            model_name='assetticksummary',
            index=models.Index(fields=['type'], name='asset_tick_summary_type_idx'),
        ),
        migrations.AddIndex(
            model_name='assetticksummary',
            index=models.Index(fields=['sym'], name='asset_tick_summary_sym_idx'),
        ),
        migrations.AddIndex(
            model_name='assetticksummary',
            index=models.Index(fields=['dt'], name='asset_tick_summary_dt_idx'),
        ),
    ]
