# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 00:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_owner', models.BooleanField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('cash', 'Cash'), ('stocks', 'Stocks'), ('canadian', 'Canadian Stock'), ('otc', 'OTC'), ('forex', 'Forex'), ('futures', 'Futures'), ('indexes', 'Indexes')], max_length=12)),
                ('target_type', models.CharField(choices=[('cash', 'Cash'), ('stocks', 'Stocks'), ('canadian', 'Canadian Stock'), ('otc', 'OTC'), ('forex', 'Forex'), ('futures', 'Futures'), ('indexes', 'Indexes')], max_length=12)),
                ('source_sym', models.CharField(max_length=12)),
                ('target_sym', models.CharField(max_length=12)),
                ('status', models.CharField(choices=[('opened', 'Opened'), ('closed', 'closed'), ('cancelled', 'cancelled')], default='opened', max_length=12)),
                ('amount', models.BigIntegerField()),
                ('price', models.BigIntegerField()),
                ('dt', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(null=True)),
                ('cancelled_at', models.DateTimeField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Account')),
            ],
        ),
        migrations.AlterField(
            model_name='assetticksummary',
            name='type',
            field=models.CharField(choices=[('cash', 'Cash'), ('stocks', 'Stocks'), ('canadian', 'Canadian Stock'), ('otc', 'OTC'), ('forex', 'Forex'), ('futures', 'Futures'), ('indexes', 'Indexes')], default='stocks', max_length=12),
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(through='app.GameMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Game'),
        ),
        migrations.AddField(
            model_name='account',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['source_type', 'source_sym'], name='order_source_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['target_type', 'target_sym'], name='order_target_idx'),
        ),
    ]
